alias: EPaper Tags - API Ninjas - Trivia
description: "Show a trivia question every hour, with the answer only being revealed after 30 minutes!"
trigger:
  - platform: time_pattern
    minutes: /30
action:
  - service: open_epaper_link.drawcustom
    data:
      background: white
      rotate: 0
      payload:
        - type: icon
          value: message-question
          x: 1
          "y": 1
          size: 32
          color: red
        - type: text
          value: >-
            {% set topic_object = {
              "artliterature":      "Art & Literature",
              "language":           "Language",
              "sciencenature":      "Science & Nature",
              "general":            "General Knowledge",
              "fooddrink":          "Food & Drink",
              "peopleplaces":       "People & Places",
              "geography":          "Geography",
              "historyholidays":    "History & Holidays",
              "entertainment":      "Entertainment",
              "toysgames":          "Toys & Games",
              "music":              "Music",
              "mathematics":        "Mathematics",
              "religionmythology":  "Religion & Mythology",
              "sportsleisure":      "Sports & Leisure",
              "question":           "Question",
              "":                   "Trivia"
            } %}  {% set topic_key =
            state_attr('sensor.api_ninja_trivia','category') | string |
            default("question") %}  {{topic_object[topic_key]}}
          font: ../../media/GothamRnd-Bold.ttf
          x: 35
          "y": >-
            {% set cat_len = state_attr('sensor.api_ninja_trivia','question') |
            length | int %} {{ 1 if cat_len < 16 else 7 | int }}
          size: >-
            {% set cat_len = state_attr('sensor.api_ninja_trivia','question') |
            length | int %} {{ 30 if cat_len < 16 else 23 | int }}
          color: red
          anchor: lt
          y_padding: 0
          spacing: 2
        - type: text
          value: "{{state_attr('sensor.api_ninja_trivia','question') | string }}"
          font: ../../media/GothamRnd-Bold.ttf
          x: 15
          "y": 38
          size: >-
            {% set string_len = state_attr('sensor.api_ninja_trivia','question')
            | length | int %} {% if string_len <= 50 %}
              22
            {% elif string_len <= 60 %}
              18
            {% elif string_len <= 100 %}
              16
            {% elif string_len <= 150 %}
              12  
            {% elif string_len <= 200 %}
              10
            {% else %} 
              8
            {% endif %}
          color: black
          anchor: lt
          max_width: 266
          y_padding: 0
          spacing: 2
        - type: text
          value: |-
            {% if now().minute < 30 %}
              ...???
            {% else %}
              {{state_attr('sensor.api_ninja_trivia','answer') | string }}
            {% endif %}
          font: ../../media/GothamRnd-Bold.ttf
          x: 5
          size: |-
            {% if now().minute < 30 %}
              28
            {% else %}
              {% set string_len = state_attr('sensor.api_ninja_trivia','answer') | length | int %}
              {% if string_len <= 20 %}
                28
              {% elif string_len <= 50 %}
                20
              {% elif string_len <= 60 %}
                18
              {% elif string_len <= 100 %}
                16
              {% elif string_len <= 150 %}
                12 
              {% else %} 
                8
              {% endif %}
            {% endif %}
          color: red
          anchor: lt
          max_width: 291
          y_padding: 8
          spacing: 2
    target:
      entity_id:
        - open_epaper_link.000002123456ABC
mode: restart
